name: Bug Found
description: Report a bug for Bracketed or BracketedBeta!
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: dropdown
    id: commandtype
    attributes:
      label: "What type of command type is erroring?"
      options:
        - Context Menu
        - Slash Commands
    validations:
      required: true

  - type: input
    id: command
    attributes:
      label: "What is the name of this command?"
      placeholder: "I'm not sure..."
    validations:
      required: false
